# Gosec security scanner configuration
# See: https://github.com/securego/gosec
#
# Recommended usage:
#   gosec -exclude-generated ./...           # Default build (excludes TUI/CLI)
#   gosec -tags=all -exclude-generated ./... # All variants
#   gosec -tags=tui -exclude-generated ./cmd/tui/... # TUI only
#
# Note: Golang SSA analysis errors are expected due to build tag architecture.
# These errors occur when gosec's internal type checker encounters packages that
# are conditionally compiled based on build tags. They do not affect:
#   - The actual Go compiler (code builds successfully)
#   - Security analysis results (still reports 0 issues)
#   - Code correctness (all tests pass)
#
# The errors are informational and can be safely ignored as they represent
# limitations in gosec's static analysis, not actual code issues.

# Global settings
global:
  # Disable SSA analysis for packages with complex build tag dependencies
  # This reduces false positive import errors in the output
  nosec: false

  # Show ignored issues for transparency
  show-ignored: false

  # Audit mode - stricter checking
  audit: false

# Excluded directories (generated/vendored code)
exclude-dirs:
  - "api/gen"  # Generated protobuf code
  - "vendor"   # Third-party dependencies
  - "test/testdata" # Test fixtures

# Severity threshold
severity: "low"

# Confidence threshold
confidence: "low"
