# Example lippycat configuration with Phase 3 TCP optimizations

# Packet Capture Configuration
# pcap_timeout_ms: 200  # PCAP read timeout in milliseconds (default: 200)
                        # Controls how often capture goroutines check for shutdown signals
                        # Lower values (50-100ms) = faster shutdown response, potentially choppy display
                        # Higher values (200-500ms) = smoother display, slightly slower shutdown
                        # Can also be set via env var: LIPPYCAT_PCAP_TIMEOUT_MS=200

# Virtual Interface Configuration (for sniff and process commands)
# virtual_interface:
#   enabled: false              # Enable virtual network interface for packet injection
#   name: "lc0"                 # Interface name (default: lc0)
#   type: "tap"                 # Interface type: tap (Layer 2) or tun (Layer 3)
#   buffer_size: 4096           # Injection queue buffer size (packets)

voip:
  # Basic TCP configuration
  max_goroutines: 1000
  tcp_cleanup_interval: 60s
  tcp_buffer_max_age: 300s
  tcp_stream_max_queue_time: 120s
  max_tcp_buffers: 10000
  tcp_stream_timeout: 600s
  tcp_assembler_max_pages: 100

  # Performance Mode Selection
  # Options: "balanced", "throughput", "latency", "memory"
  tcp_performance_mode: "balanced"

  # Buffer Strategy
  # Options: "adaptive", "fixed", "ring"
  tcp_buffer_strategy: "adaptive"

  # Backpressure and Memory Optimization
  enable_backpressure: true
  memory_optimization: false

  # Advanced Performance Tuning
  tcp_buffer_pool_size: 1000
  tcp_batch_size: 32
  tcp_io_threads: 4
  tcp_compression_level: 1
  tcp_memory_limit: 104857600  # 100MB
  tcp_latency_optimization: false

  # Security Configuration
  security:
    # Call-ID Sanitization for preventing information leakage in logs
    sanitize_call_ids: false          # Set to true to enable Call-ID sanitization
    call_id_hash_length: 8            # Length of hash prefix for sanitized Call-IDs
    call_id_max_log_length: 16        # Maximum Call-ID length before sanitization kicks in

    # PCAP File Encryption for sensitive deployments
    enable_pcap_encryption: false     # Set to true to enable PCAP encryption

    # Content-Length Bounds Validation for DoS protection
    max_content_length: 1048576       # Maximum Content-Length value (1MB default)
    max_message_size: 2097152         # Maximum total SIP message size (2MB default)

  # Encryption Configuration (only used when enable_pcap_encryption is true)
  encryption:
    enabled: false                    # Master encryption toggle
    key_file: "/etc/lippycat/keys/pcap.key"  # Path to encryption key file (will be generated if missing)
    algorithm: "aes-256-gcm"         # Encryption algorithm (only aes-256-gcm supported)
    key_derive: "pbkdf2"             # Key derivation method (only pbkdf2 supported)
    pbkdf2_iterations: 100000        # PBKDF2 iterations for key derivation

# Performance Mode Examples:

# High Throughput Configuration
# voip:
#   tcp_performance_mode: "throughput"
#   tcp_buffer_strategy: "ring"
#   max_goroutines: 2000
#   tcp_batch_size: 64
#   enable_backpressure: true

# Low Latency Configuration
# voip:
#   tcp_performance_mode: "latency"
#   tcp_buffer_strategy: "fixed"
#   tcp_batch_size: 1
#   tcp_latency_optimization: true
#   tcp_cleanup_interval: 30s

# Memory Optimized Configuration
# voip:
#   tcp_performance_mode: "memory"
#   tcp_buffer_strategy: "adaptive"
#   max_goroutines: 100
#   max_tcp_buffers: 1000
#   memory_optimization: true
#   tcp_memory_limit: 52428800  # 50MB

# Security Enhanced Configuration (for sensitive deployments)
# voip:
#   security:
#     sanitize_call_ids: true           # Enable Call-ID sanitization in logs
#     call_id_hash_length: 12          # Longer hash for better anonymization
#     call_id_max_log_length: 8        # Shorter threshold for aggressive sanitization
#     enable_pcap_encryption: true     # Enable PCAP file encryption
#     max_content_length: 65536        # Strict 64KB Content-Length limit
#     max_message_size: 131072         # Strict 128KB total message limit
#   encryption:
#     enabled: true                     # Master encryption toggle
#     key_file: "/secure/keys/lippycat-pcap.key"  # Secure key file location
#     algorithm: "aes-256-gcm"         # Strong encryption algorithm
#     pbkdf2_iterations: 200000        # Higher iterations for stronger key derivation