// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpfadmission

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type admissionAddress struct {
	_       structs.HostLayout
	Domain  uint32
	Family  uint8
	Pad     [3]uint8
	Address [16]uint8
}

type admissionControl struct {
	_          structs.HostLayout
	Generation uint64
	Mode       uint32
	NoFilters  uint32
}

type admissionEndpoint struct {
	_       structs.HostLayout
	Domain  uint32
	Address [16]uint8
	Port    uint16
	Family  uint8
	Pad     uint8
}

type admissionPrefix struct {
	_       structs.HostLayout
	Bits    uint32
	Address admissionAddress
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	admissionMapAddresses         = "addresses"
	admissionMapControls          = "controls"
	admissionMapCounters          = "counters"
	admissionMapDecisions         = "decisions"
	admissionMapEndpoints         = "endpoints"
	admissionMapPortPolicy        = "port_policy"
	admissionMapPrefixes          = "prefixes"
	admissionProgAdmit            = "admit"
	admissionVarCaptureLength     = "capture_length"
	admissionVarDomain            = "domain"
	admissionVarEspEnabled        = "esp_enabled"
	admissionVarRestrictRtpPorts  = "restrict_rtp_ports"
	admissionVarRestrictSipPorts  = "restrict_sip_ports"
	admissionVarShadowSampleEvery = "shadow_sample_every"
	admissionVarUdpOnly           = "udp_only"
)

// loadAdmission returns the embedded CollectionSpec for admission.
func loadAdmission() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AdmissionBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load admission: %w", err)
	}

	return spec, err
}

// loadAdmissionObjects loads admission and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*admissionObjects
//	*admissionPrograms
//	*admissionMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAdmissionObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadAdmission()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// admissionSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type admissionSpecs struct {
	admissionProgramSpecs
	admissionMapSpecs
	admissionVariableSpecs
}

// admissionProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type admissionProgramSpecs struct {
	Admit *ebpf.ProgramSpec `ebpf:"admit"`
}

// admissionMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type admissionMapSpecs struct {
	Addresses  *ebpf.MapSpec `ebpf:"addresses"`
	Controls   *ebpf.MapSpec `ebpf:"controls"`
	Counters   *ebpf.MapSpec `ebpf:"counters"`
	Decisions  *ebpf.MapSpec `ebpf:"decisions"`
	Endpoints  *ebpf.MapSpec `ebpf:"endpoints"`
	PortPolicy *ebpf.MapSpec `ebpf:"port_policy"`
	Prefixes   *ebpf.MapSpec `ebpf:"prefixes"`
}

// admissionVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type admissionVariableSpecs struct {
	CaptureLength     *ebpf.VariableSpec `ebpf:"capture_length"`
	Domain            *ebpf.VariableSpec `ebpf:"domain"`
	EspEnabled        *ebpf.VariableSpec `ebpf:"esp_enabled"`
	RestrictRtpPorts  *ebpf.VariableSpec `ebpf:"restrict_rtp_ports"`
	RestrictSipPorts  *ebpf.VariableSpec `ebpf:"restrict_sip_ports"`
	ShadowSampleEvery *ebpf.VariableSpec `ebpf:"shadow_sample_every"`
	UdpOnly           *ebpf.VariableSpec `ebpf:"udp_only"`
}

// admissionObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAdmissionObjects or ebpf.CollectionSpec.LoadAndAssign.
type admissionObjects struct {
	admissionPrograms
	admissionMaps
	admissionVariables
}

func (o *admissionObjects) Close() error {
	return _AdmissionClose(
		&o.admissionPrograms,
		&o.admissionMaps,
	)
}

// admissionMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAdmissionObjects or ebpf.CollectionSpec.LoadAndAssign.
type admissionMaps struct {
	Addresses  *ebpf.Map `ebpf:"addresses"`
	Controls   *ebpf.Map `ebpf:"controls"`
	Counters   *ebpf.Map `ebpf:"counters"`
	Decisions  *ebpf.Map `ebpf:"decisions"`
	Endpoints  *ebpf.Map `ebpf:"endpoints"`
	PortPolicy *ebpf.Map `ebpf:"port_policy"`
	Prefixes   *ebpf.Map `ebpf:"prefixes"`
}

func (m *admissionMaps) Close() error {
	return _AdmissionClose(
		m.Addresses,
		m.Controls,
		m.Counters,
		m.Decisions,
		m.Endpoints,
		m.PortPolicy,
		m.Prefixes,
	)
}

// admissionVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAdmissionObjects or ebpf.CollectionSpec.LoadAndAssign.
type admissionVariables struct {
	CaptureLength     *ebpf.Variable `ebpf:"capture_length"`
	Domain            *ebpf.Variable `ebpf:"domain"`
	EspEnabled        *ebpf.Variable `ebpf:"esp_enabled"`
	RestrictRtpPorts  *ebpf.Variable `ebpf:"restrict_rtp_ports"`
	RestrictSipPorts  *ebpf.Variable `ebpf:"restrict_sip_ports"`
	ShadowSampleEvery *ebpf.Variable `ebpf:"shadow_sample_every"`
	UdpOnly           *ebpf.Variable `ebpf:"udp_only"`
}

// admissionPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAdmissionObjects or ebpf.CollectionSpec.LoadAndAssign.
type admissionPrograms struct {
	Admit *ebpf.Program `ebpf:"admit"`
}

func (p *admissionPrograms) Close() error {
	return _AdmissionClose(
		p.Admit,
	)
}

func _AdmissionClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed admission_bpfel.o
var _AdmissionBytes []byte
