//go:build li

// Code generated by xgen from ETSI TS 103 280 XSD. DO NOT EDIT.

package schema

// ShortString ...
type ShortString string

// LongString ...
type LongString string

// LIID ...
type LIID string

// UTCDateTime ...
type UTCDateTime string

// UTCMicrosecondDateTime ...
type UTCMicrosecondDateTime string

// QualifiedDateTime ...
type QualifiedDateTime string

// QualifiedMicrosecondDateTime ...
type QualifiedMicrosecondDateTime string

// InternationalE164 ...
type InternationalE164 string

// IMSI ...
type IMSI string

// IMEI ...
type IMEI string

// IMEICheckDigit ...
type IMEICheckDigit string

// IMEISV ...
type IMEISV string

// IPv4Address ...
type IPv4Address string

// IPv4CIDR ...
type IPv4CIDR string

// IPv6Address ...
type IPv6Address string

// IPv6CIDR ...
type IPv6CIDR string

// IPAddress ...
type IPAddress struct {
	IPv4Address *string `xml:"IPv4Address"`
	IPv6Address *string `xml:"IPv6Address"`
}

// IPCIDR ...
type IPCIDR struct {
	IPv4CIDR *string `xml:"IPv4CIDR"`
	IPv6CIDR *string `xml:"IPv6CIDR"`
}

// TCPPort ...
type TCPPort int

// TCPPortRange ...
type TCPPortRange struct {
	Start int `xml:"start"`
	End   int `xml:"end"`
}

// UDPPort ...
type UDPPort int

// UDPPortRange ...
type UDPPortRange struct {
	Start int `xml:"start"`
	End   int `xml:"end"`
}

// Port ...
type Port struct {
	TCPPort *int `xml:"TCPPort"`
	UDPPort *int `xml:"UDPPort"`
}

// PortRange ...
type PortRange struct {
	TCPPortRange *TCPPortRange `xml:"TCPPortRange"`
	UDPPortRange *UDPPortRange `xml:"UDPPortRange"`
}

// IPAddressPort ...
type IPAddressPort struct {
	Address *IPAddress `xml:"address"`
	Port    *Port      `xml:"port"`
}

// IPAddressPortRange ...
type IPAddressPortRange struct {
	Address   *IPAddress `xml:"address"`
	PortRange *PortRange `xml:"portRange"`
}

// MACAddress ...
type MACAddress string

// EmailAddress ...
type EmailAddress string

// UUID ...
type UUID string

// ISOCountryCode ...
type ISOCountryCode string

// SIPURI ...
type SIPURI string

// TELURI ...
type TELURI string

// WGS84CoordinateDecimal ...
type WGS84CoordinateDecimal struct {
	Latitude  string `xml:"latitude"`
	Longitude string `xml:"longitude"`
}

// WGS84LatitudeDecimal ...
type WGS84LatitudeDecimal string

// WGS84LongitudeDecimal ...
type WGS84LongitudeDecimal string

// WGS84CoordinateAngular ...
type WGS84CoordinateAngular struct {
	Latitude  string `xml:"latitude"`
	Longitude string `xml:"longitude"`
}

// WGS84LatitudeAngular ...
type WGS84LatitudeAngular string

// WGS84LongitudeAngular ...
type WGS84LongitudeAngular string

// SUPIIMSI ...
type SUPIIMSI string

// SUPINAI ...
type SUPINAI string

// SUCI ...
type SUCI string

// PEIIMEI ...
type PEIIMEI string

// PEIIMEICheckDigit ...
type PEIIMEICheckDigit string

// PEIIMEISV ...
type PEIIMEISV string

// GPSIMSISDN ...
type GPSIMSISDN string

// GPSINAI ...
type GPSINAI string

// NAI ...
type NAI string

// LDID ...
type LDID string

// InternationalizedEmailAddress ...
type InternationalizedEmailAddress string

// EUI64 ...
type EUI64 string

// CGI ...
type CGI string

// ECGI ...
type ECGI string

// NCGI ...
type NCGI string

// ICCID ...
type ICCID string

// IPProtocol ...
type IPProtocol int

// VLANID ...
type VLANID int

// VIN ...
type VIN string

// ServiceAccessIdentifier ...
type ServiceAccessIdentifier string

// EUICCID ...
type EUICCID string

// APN ...
type APN string

// DNN ...
type DNN string

// H323URI ...
type H323URI string

// IMPU ...
type IMPU string

// IMPI ...
type IMPI string

// VRF ...
type VRF string
