//go:build li

// Code generated by xgen from ETSI TS 103 221-1 HashedID XSD. DO NOT EDIT.

package schema

// HashContext ...
type HashContext struct {
	HashAlgorithm string `xml:"hashAlgorithm"`
	Salt          string `xml:"salt"`
	*GenericObject
}

// HashAlgorithm ...
type HashAlgorithm string

// Salt ...
type Salt string

// HashedIdentifier ...
type HashedIdentifier struct {
	HashContextID      *GenericObjectID `xml:"hashContextID"`
	TargetIdentityType *ShortString     `xml:"targetIdentityType"`
	HashDigest         string           `xml:"hashDigest"`
}
