//go:build li

// Code generated by xgen from ETSI TS 103 221-1 XSD. DO NOT EDIT.

package schema

// X1Request ...
type X1Request *RequestContainer

// X1Response ...
type X1Response *ResponseContainer

// X1TopLevelErrorResponse ...
type X1TopLevelErrorResponse *TopLevelErrorResponse

// RequestContainer ...
type RequestContainer struct {
	X1RequestMessage []*X1RequestMessage `xml:"x1RequestMessage"`
}

// ResponseContainer ...
type ResponseContainer struct {
	X1ResponseMessage []*X1ResponseMessage `xml:"x1ResponseMessage"`
}

// X1RequestMessage ...
type X1RequestMessage struct {
	AdmfIdentifier   string                        `xml:"admfIdentifier"`
	NeIdentifier     string                        `xml:"neIdentifier"`
	MessageTimestamp *QualifiedMicrosecondDateTime `xml:"messageTimestamp"`
	Version          string                        `xml:"version"`
	X1TransactionId  *UUID                         `xml:"x1TransactionId"`
}

// X1ResponseMessage ...
type X1ResponseMessage struct {
	AdmfIdentifier   string                        `xml:"admfIdentifier"`
	NeIdentifier     string                        `xml:"neIdentifier"`
	MessageTimestamp *QualifiedMicrosecondDateTime `xml:"messageTimestamp"`
	Version          string                        `xml:"version"`
	X1TransactionId  *UUID                         `xml:"x1TransactionId"`
}

// XId ...
type XId *UUID

// DId ...
type DId *UUID

// X1TransactionId ...
type X1TransactionId *UUID

// AdmfIdentifier ...
type AdmfIdentifier string

// NeIdentifier ...
type NeIdentifier string

// Version ...
type Version string

// TopLevelErrorResponse ...
type TopLevelErrorResponse struct {
	AdmfIdentifier   string                        `xml:"admfIdentifier"`
	NeIdentifier     string                        `xml:"neIdentifier"`
	MessageTimestamp *QualifiedMicrosecondDateTime `xml:"messageTimestamp"`
	Version          string                        `xml:"version"`
}

// ErrorResponse ...
type ErrorResponse struct {
	RequestMessageType   string                `xml:"requestMessageType"`
	ErrorInformation     *ErrorInformation     `xml:"errorInformation"`
	ExtensionInformation *ExtensionInformation `xml:"extensionInformation"`
	*X1ResponseMessage
}

// RequestMessageType ...
type RequestMessageType string

// ErrorInformation ...
type ErrorInformation struct {
	ErrorCode        int    `xml:"errorCode"`
	ErrorDescription string `xml:"errorDescription"`
}

// ExtensionInformation ...
type ExtensionInformation struct {
	ExtensionSpecification     string `xml:"extensionSpecification"`
	ExtendedRequestMessageType string `xml:"extendedRequestMessageType"`
}

// ExtensionSpecification ...
type ExtensionSpecification string

// ActivateTaskRequest ...
type ActivateTaskRequest struct {
	TaskDetails *TaskDetails `xml:"taskDetails"`
	*X1RequestMessage
}

// TaskDetails ...
type TaskDetails struct {
	XId                           *UUID                          `xml:"xId"`
	TargetIdentifiers             *ListOfTargetIdentifiers       `xml:"targetIdentifiers"`
	DeliveryType                  string                         `xml:"deliveryType"`
	ListOfDIDs                    *ListOfDids                    `xml:"listOfDIDs"`
	ListOfMediationDetails        *ListOfMediationDetails        `xml:"listOfMediationDetails"`
	CorrelationID                 *int                           `xml:"correlationID"`
	ImplicitDeactivationAllowed   *bool                          `xml:"implicitDeactivationAllowed"`
	ProductID                     *UUID                          `xml:"productID"`
	ListOfServiceTypes            *ListOfServiceTypes            `xml:"listOfServiceTypes"`
	TaskDetailsExtensions         []*TaskDetailsExtensions       `xml:"taskDetailsExtensions"`
	ListOfTrafficPolicyReferences *ListOfTrafficPolicyReferences `xml:"listOfTrafficPolicyReferences"`
}

// ListOfTargetIdentifiers ...
type ListOfTargetIdentifiers struct {
	TargetIdentifier []*TargetIdentifier `xml:"targetIdentifier"`
}

// TargetIdentifier ...
type TargetIdentifier struct {
	E164Number                    *InternationalE164             `xml:"e164Number"`
	Imsi                          *IMSI                          `xml:"imsi"`
	Imei                          *IMEI                          `xml:"imei"`
	MacAddress                    *MACAddress                    `xml:"macAddress"`
	Ipv4Address                   *IPv4Address                   `xml:"ipv4Address"`
	Ipv6Address                   *IPv6Address                   `xml:"ipv6Address"`
	Ipv4Cidr                      *IPCIDR                        `xml:"ipv4Cidr"`
	Ipv6Cidr                      *IPv6CIDR                      `xml:"ipv6Cidr"`
	TcpPort                       *TCPPort                       `xml:"tcpPort"`
	TcpPortRange                  *TCPPortRange                  `xml:"tcpPortRange"`
	TcpPortList                   *TCPPortList                   `xml:"tcpPortList"`
	UdpPort                       *UDPPort                       `xml:"udpPort"`
	UdpPortRange                  *UDPPortRange                  `xml:"udpPortRange"`
	UdpPortList                   *UDPPortList                   `xml:"udpPortList"`
	EmailAddress                  *EmailAddress                  `xml:"emailAddress"`
	InternationalizedEmailAddress *InternationalizedEmailAddress `xml:"internationalizedEmailAddress"`
	SipUri                        *SIPURI                        `xml:"sipUri"`
	TelUri                        *TELURI                        `xml:"telUri"`
	H323Uri                       *H323URI                       `xml:"h323Uri"`
	Impu                          *IMPU                          `xml:"impu"`
	Impi                          *IMPI                          `xml:"impi"`
	Nai                           *NAI                           `xml:"nai"`
	RadiusAttribute               *string                        `xml:"radiusAttribute"`
	GtpuTunnelId                  *int                           `xml:"gtpuTunnelId"`
	GtpcTunnelId                  *int                           `xml:"gtpcTunnelId"`
	CallPartyRole                 *string                        `xml:"callPartyRole"`
	NonLocalIdentifier            *string                        `xml:"nonLocalIdentifier"`
	Supiimsi                      *SUPIIMSI                      `xml:"supiimsi"`
	Supinai                       *SUPINAI                       `xml:"supinai"`
	Suci                          *SUCI                          `xml:"suci"`
	PeiImei                       *PEIIMEI                       `xml:"peiImei"`
	PeiImeiCheckDigit             *PEIIMEICheckDigit             `xml:"peiImeiCheckDigit"`
	PeiImeisv                     *PEIIMEISV                     `xml:"peiImeisv"`
	GpsiMsisdn                    *GPSIMSISDN                    `xml:"gpsiMsisdn"`
	GpsiNai                       *GPSINAI                       `xml:"gpsiNai"`
	Eui64                         *EUI64                         `xml:"eui64"`
	ServiceAccessIdentifier       *ServiceAccessIdentifier       `xml:"serviceAccessIdentifier"`
	HashedIdentifier              *HashedIdentifier              `xml:"hashedIdentifier"`
	TargetIdentifierExtension     *TargetIdentifierExtension     `xml:"targetIdentifierExtension"`
	Vrf                           *VRF                           `xml:"vrf"`
}

// TCPPortList ...
type TCPPortList struct {
	TcpPort []*TCPPort `xml:"tcpPort"`
}

// UDPPortList ...
type UDPPortList struct {
	UdpPort []*UDPPort `xml:"udpPort"`
}

// GtpTunnelId ...
type GtpTunnelId int

// CallPartyRole ...
type CallPartyRole string

// NonLocalIdentifier ...
type NonLocalIdentifier string

// TargetIdentifierExtension ...
type TargetIdentifierExtension struct {
	*Extension
}

// MediationDetails ...
type MediationDetails struct {
	LIID                          *LIID                          `xml:"LIID"`
	DeliveryType                  string                         `xml:"deliveryType"`
	StartTime                     *QualifiedMicrosecondDateTime  `xml:"StartTime"`
	EndTime                       *QualifiedMicrosecondDateTime  `xml:"EndTime"`
	ListOfDIDs                    *ListOfDids                    `xml:"listOfDIDs"`
	MediationDetailsExtensions    []*MediationDetailsExtensions  `xml:"mediationDetailsExtensions"`
	ServiceScopingOptions         *ListOfServiceScopingOptions   `xml:"serviceScopingOptions"`
	ListOfTrafficPolicyReferences *ListOfTrafficPolicyReferences `xml:"listOfTrafficPolicyReferences"`
}

// ListOfServiceScopingOptions ...
type ListOfServiceScopingOptions struct {
	ServiceScopingOptions []*ServiceScopingOptions `xml:"serviceScopingOptions"`
}

// ServiceScopingOptions ...
type ServiceScopingOptions struct {
	ServiceType                           *ListOfServiceTypes  `xml:"serviceType"`
	LocationType                          *LocationTypeOptions `xml:"locationType"`
	SuspendOnOutboundInternationalRoaming *bool                `xml:"suspendOnOutboundInternationalRoaming"`
	ReportPostDialledDigits               *bool                `xml:"reportPostDialledDigits"`
}

// ListOfServiceTypes ...
type ListOfServiceTypes struct {
	ServiceType []string `xml:"serviceType"`
}

// ServiceType ...
type ServiceType string

// LocationTypeOptions ...
type LocationTypeOptions struct {
	DoNotReport         *string              `xml:"doNotReport"`
	ListOfLocationTypes *ListOfLocationTypes `xml:"listOfLocationTypes"`
}

// ListOfLocationTypes ...
type ListOfLocationTypes struct {
	LocationType []*LocationType `xml:"locationType"`
}

// LocationType ...
type LocationType struct {
	BeginningAndEnd *bool `xml:"beginningAndEnd"`
	UponChange      *bool `xml:"uponChange"`
	LALS            *bool `xml:"LALS"`
}

// DeliveryType ...
type DeliveryType string

// MediationDeliveryType ...
type MediationDeliveryType string

// ListOfDids ...
type ListOfDids struct {
	DId  []*UUID `xml:"dId"`
	DSId []*UUID `xml:"dSId"`
}

// ListOfTrafficPolicyReferences ...
type ListOfTrafficPolicyReferences struct {
	TrafficPolicyReference []*GenericObjectID `xml:"trafficPolicyReference"`
}

// TrafficPolicyReference ...
type TrafficPolicyReference *UUID

// ListOfMediationDetails ...
type ListOfMediationDetails struct {
	MediationDetails []*MediationDetails `xml:"mediationDetails"`
}

// TaskDetailsExtensions ...
type TaskDetailsExtensions struct {
	*Extension
}

// MediationDetailsExtensions ...
type MediationDetailsExtensions struct {
	*Extension
}

// TaskStatusExtensions ...
type TaskStatusExtensions struct {
	*Extension
}

// Extension ...
type Extension struct {
	Owner string `xml:"Owner"`
}

// TaskIssueExtensions ...
type TaskIssueExtensions struct {
	*Extension
}

// NEIssueExtensions ...
type NEIssueExtensions struct {
	*Extension
}

// ActivateTaskResponse ...
type ActivateTaskResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// OK ...
type OK string

// OKAckAndComplete ...
type OKAckAndComplete string

// ModifyTaskRequest ...
type ModifyTaskRequest struct {
	TaskDetails *TaskDetails `xml:"taskDetails"`
	*X1RequestMessage
}

// ModifyTaskResponse ...
type ModifyTaskResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// DeactivateTaskRequest ...
type DeactivateTaskRequest struct {
	XId *UUID `xml:"xId"`
	*X1RequestMessage
}

// DeactivateTaskResponse ...
type DeactivateTaskResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// DeactivateAllTasksRequest ...
type DeactivateAllTasksRequest struct {
	*X1RequestMessage
}

// DeactivateAllTasksResponse ...
type DeactivateAllTasksResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// CreateDestinationRequest ...
type CreateDestinationRequest struct {
	DestinationDetails *DestinationDetails `xml:"destinationDetails"`
	*X1RequestMessage
}

// DestinationDetails ...
type DestinationDetails struct {
	DId                          *UUID                           `xml:"dId"`
	FriendlyName                 *string                         `xml:"friendlyName"`
	DeliveryType                 string                          `xml:"deliveryType"`
	DeliveryAddress              *DeliveryAddress                `xml:"deliveryAddress"`
	DestinationDetailsExtensions []*DestinationDetailsExtensions `xml:"destinationDetailsExtensions"`
}

// DeliveryAddress ...
type DeliveryAddress struct {
	IpAddressAndPort *IPAddressPort     `xml:"ipAddressAndPort"`
	E164Number       *InternationalE164 `xml:"e164Number"`
	Uri              *string            `xml:"uri"`
	EmailAddress     *EmailAddress      `xml:"emailAddress"`
}

// DestinationDetailsExtensions ...
type DestinationDetailsExtensions struct {
	*Extension
}

// CreateDestinationResponse ...
type CreateDestinationResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// ModifyDestinationRequest ...
type ModifyDestinationRequest struct {
	DestinationDetails *DestinationDetails `xml:"destinationDetails"`
	*X1RequestMessage
}

// ModifyDestinationResponse ...
type ModifyDestinationResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// RemoveDestinationRequest ...
type RemoveDestinationRequest struct {
	DId *UUID `xml:"dId"`
	*X1RequestMessage
}

// RemoveDestinationResponse ...
type RemoveDestinationResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// RemoveAllDestinationsRequest ...
type RemoveAllDestinationsRequest struct {
	*X1RequestMessage
}

// RemoveAllDestinationsResponse ...
type RemoveAllDestinationsResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// GetTaskDetailsRequest ...
type GetTaskDetailsRequest struct {
	XId *UUID `xml:"xId"`
	*X1RequestMessage
}

// GetTaskDetailsResponse ...
type GetTaskDetailsResponse struct {
	TaskResponseDetails *TaskResponseDetails `xml:"taskResponseDetails"`
	*X1ResponseMessage
}

// TaskResponseDetails ...
type TaskResponseDetails struct {
	TaskDetails *TaskDetails `xml:"taskDetails"`
	TaskStatus  *TaskStatus  `xml:"taskStatus"`
}

// TaskStatus ...
type TaskStatus struct {
	ProvisioningStatus     string                        `xml:"provisioningStatus"`
	ListOfFaults           *ListOfFaults                 `xml:"listOfFaults"`
	TimeOfLastIntercept    *QualifiedMicrosecondDateTime `xml:"timeOfLastIntercept"`
	AmountOfX2Data         *int                          `xml:"amountOfX2Data"`
	AmountOfX3Data         *int                          `xml:"amountOfX3Data"`
	TimeOfLastModification *QualifiedMicrosecondDateTime `xml:"timeOfLastModification"`
	NumberOfModifications  *int                          `xml:"numberOfModifications"`
	TaskStatusExtensions   []*TaskStatusExtensions       `xml:"taskStatusExtensions"`
}

// ProvisioningStatus ...
type ProvisioningStatus string

// ListOfFaults ...
type ListOfFaults struct {
	UnresolvedFault []*ErrorInformation `xml:"unresolvedFault"`
}

// GetDestinationDetailsRequest ...
type GetDestinationDetailsRequest struct {
	DId *UUID `xml:"dId"`
	*X1RequestMessage
}

// GetDestinationDetailsResponse ...
type GetDestinationDetailsResponse struct {
	DestinationResponseDetails *DestinationResponseDetails `xml:"destinationResponseDetails"`
	*X1ResponseMessage
}

// DestinationResponseDetails ...
type DestinationResponseDetails struct {
	DestinationDetails *DestinationDetails `xml:"destinationDetails"`
	DestinationStatus  *DestinationStatus  `xml:"destinationStatus"`
}

// DestinationStatus ...
type DestinationStatus struct {
	DestinationDeliveryStatus string        `xml:"destinationDeliveryStatus"`
	ListOfFaults              *ListOfFaults `xml:"listOfFaults"`
}

// DestinationDeliveryStatus ...
type DestinationDeliveryStatus string

// GetNEStatusRequest ...
type GetNEStatusRequest struct {
	*X1RequestMessage
}

// GetNEStatusResponse ...
type GetNEStatusResponse struct {
	NeStatusDetails *NeStatusDetails `xml:"neStatusDetails"`
	*X1ResponseMessage
}

// NeStatusDetails ...
type NeStatusDetails struct {
	NeStatus     string        `xml:"neStatus"`
	ListOfFaults *ListOfFaults `xml:"listOfFaults"`
}

// NeStatus ...
type NeStatus string

// GetAllDetailsRequest ...
type GetAllDetailsRequest struct {
	*X1RequestMessage
}

// GetAllDetailsResponse ...
type GetAllDetailsResponse struct {
	NeStatusDetails                    *NeStatusDetails                    `xml:"neStatusDetails"`
	ListOfTaskResponseDetails          *ListOfTaskResponseDetails          `xml:"listOfTaskResponseDetails"`
	ListOfDestinationResponseDetails   *ListOfDestinationResponseDetails   `xml:"listOfDestinationResponseDetails"`
	ListOfGenericObjectResponseDetails *ListOfGenericObjectResponseDetails `xml:"listOfGenericObjectResponseDetails"`
	*X1ResponseMessage
}

// ListOfTaskResponseDetails ...
type ListOfTaskResponseDetails struct {
	TaskResponseDetails []*TaskResponseDetails `xml:"taskResponseDetails"`
}

// ListOfDestinationResponseDetails ...
type ListOfDestinationResponseDetails struct {
	DestinationResponseDetails []*DestinationResponseDetails `xml:"destinationResponseDetails"`
}

// ListAllDetailsRequest ...
type ListAllDetailsRequest struct {
	*X1RequestMessage
}

// ListAllDetailsResponse ...
type ListAllDetailsResponse struct {
	ListOfXIDs             *ListOfXids             `xml:"ListOfXIDs"`
	ListOfDIDs             *ListOfDids             `xml:"ListOfDIDs"`
	ListOfGenericObjectIDs *ListOfGenericObjectIDs `xml:"ListOfGenericObjectIDs"`
	*X1ResponseMessage
}

// ListOfXids ...
type ListOfXids struct {
	XId []*UUID `xml:"xId"`
}

// GetAllTaskDetailsRequest ...
type GetAllTaskDetailsRequest struct {
	*X1RequestMessage
}

// GetAllTaskDetailsResponse ...
type GetAllTaskDetailsResponse struct {
	ListOfTaskResponseDetails *ListOfTaskResponseDetails `xml:"listOfTaskResponseDetails"`
	*X1ResponseMessage
}

// GetAllDestinationDetailsRequest ...
type GetAllDestinationDetailsRequest struct {
	*X1RequestMessage
}

// GetAllDestinationDetailsResponse ...
type GetAllDestinationDetailsResponse struct {
	ListOfDestinationResponseDetails *ListOfDestinationResponseDetails `xml:"listOfDestinationResponseDetails"`
	*X1ResponseMessage
}

// GetAllGenericObjectDetailsRequest ...
type GetAllGenericObjectDetailsRequest struct {
	ObjectType *string `xml:"objectType"`
	*X1RequestMessage
}

// GetAllGenericObjectDetailsResponse ...
type GetAllGenericObjectDetailsResponse struct {
	ListOfGenericObjectResponseDetails *ListOfGenericObjectResponseDetails `xml:"listOfGenericObjectResponseDetails"`
	*X1ResponseMessage
}

// ReportTaskIssueRequest ...
type ReportTaskIssueRequest struct {
	XId                 *UUID                  `xml:"xId"`
	TaskReportType      string                 `xml:"taskReportType"`
	TaskIssueErrorCode  *int                   `xml:"taskIssueErrorCode"`
	TaskIssueDetails    *string                `xml:"taskIssueDetails"`
	TaskIssueExtensions []*TaskIssueExtensions `xml:"taskIssueExtensions"`
	*X1RequestMessage
}

// TaskReportType ...
type TaskReportType string

// ReportTaskIssueResponse ...
type ReportTaskIssueResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// ReportDestinationIssueRequest ...
type ReportDestinationIssueRequest struct {
	DId                       *UUID   `xml:"dId"`
	DestinationReportType     string  `xml:"destinationReportType"`
	DestinationIssueErrorCode *int    `xml:"destinationIssueErrorCode"`
	DestinationIssueDetails   *string `xml:"destinationIssueDetails"`
	*X1RequestMessage
}

// ReportDestinationIssueResponse ...
type ReportDestinationIssueResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// ReportNEIssueRequest ...
type ReportNEIssueRequest struct {
	TypeOfNeIssueMessage string               `xml:"typeOfNeIssueMessage"`
	Description          string               `xml:"description"`
	IssueCode            *int                 `xml:"issueCode"`
	NEIssueExtensions    []*NEIssueExtensions `xml:"nEIssueExtensions"`
	*X1RequestMessage
}

// TypeOfNeIssueMessage ...
type TypeOfNeIssueMessage string

// ReportNEIssueResponse ...
type ReportNEIssueResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// PingRequest ...
type PingRequest struct {
	*X1RequestMessage
}

// PingResponse ...
type PingResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// KeepaliveRequest ...
type KeepaliveRequest struct {
	*X1RequestMessage
}

// KeepaliveResponse ...
type KeepaliveResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// GenericObjectID ...
type GenericObjectID *UUID

// GenericObjectType ...
type GenericObjectType string

// GenericObject ...
type GenericObject struct {
	ObjectId *UUID `xml:"objectId"`
}

// CreateObjectRequest ...
type CreateObjectRequest struct {
	CreateObject *GenericObject `xml:"createObject"`
	*X1RequestMessage
}

// CreateObjectResponse ...
type CreateObjectResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// ModifyObjectRequest ...
type ModifyObjectRequest struct {
	ModifyObject *GenericObject `xml:"modifyObject"`
	*X1RequestMessage
}

// ModifyObjectResponse ...
type ModifyObjectResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// GetObjectRequest ...
type GetObjectRequest struct {
	ObjectId *UUID `xml:"objectId"`
	*X1RequestMessage
}

// GetObjectResponse ...
type GetObjectResponse struct {
	GenericObjectResponseDetails *GenericObjectResponseDetails `xml:"genericObjectResponseDetails"`
	*X1ResponseMessage
}

// GenericObjectResponseDetails ...
type GenericObjectResponseDetails struct {
	Object *GenericObject       `xml:"object"`
	Status *GenericObjectStatus `xml:"status"`
}

// ListOfGenericObjectResponseDetails ...
type ListOfGenericObjectResponseDetails struct {
	GenericObjectResponseDetails []*GenericObjectResponseDetails `xml:"genericObjectResponseDetails"`
}

// GenericObjectStatus ...
type GenericObjectStatus struct {
}

// DeleteObjectRequest ...
type DeleteObjectRequest struct {
	ObjectId *UUID `xml:"objectId"`
	*X1RequestMessage
}

// DeleteObjectResponse ...
type DeleteObjectResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}

// ListObjectsOfTypeRequest ...
type ListObjectsOfTypeRequest struct {
	ObjectType string `xml:"objectType"`
	*X1RequestMessage
}

// ListObjectsOfTypeResponse ...
type ListObjectsOfTypeResponse struct {
	ListOfObjects *ListOfGenericObjectIDs `xml:"listOfObjects"`
	*X1ResponseMessage
}

// ListOfGenericObjectIDs ...
type ListOfGenericObjectIDs struct {
	ObjectId []*UUID `xml:"objectId"`
}

// DeleteAllObjectsRequest ...
type DeleteAllObjectsRequest struct {
	*X1RequestMessage
}

// DeleteAllObjectsResponse ...
type DeleteAllObjectsResponse struct {
	OK string `xml:"oK"`
	*X1ResponseMessage
}
